<div style="color:red;">Hello World</div>
<div style="font-family: 'Times New Roman', Times, serif;">Hello World</div>
<div style="font-size:large;">Hello World</div>
<div style="font-size:small;">Hello World</div>
<div style="font-size:10px;">Hello World</div>
<div style="font-size:1.2em;">Hello World</div>
<div style="font-style:italic;">Hello World</div>
<div style="font-variant:small-caps;">Hello World</div>
<div style="font-weight:bold;">Hello World</div>
<div style="text-decoration:underline;">Hello World</div>
<div style="text-decoration:line-through">Hello World</div>
<div style="text-decoration:overline;">Hello World</div>
